version: '3'

services:
  web:
    build:
      context: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    ports:
      - '8000:8000'
    environment:
      DATABASE_URL: postgresql://username:password@postgres:5432/smscampaigner
    depends_on:
      - postgres
    networks:
      - backend

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: smscampaigner
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
    networks:
      - backend

networks:
  backend:
    driver: bridge
